name: Send Email Notification

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    env:     
      ENV: "DEV"
      RELEASE: "Release_0.0.15"
      TAG: "Release_0.0.15"
      TASK: "POC sending Email from CI CD"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Send Email Notification
        run: |
            curl --location 'https://api.courier.com/send' \
            --header 'Authorization: Bearer pk_test_VR9ADX72AYMN7DQMBBR30P4QBJEX' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "message": {
                    "to": {
                        "email": "${{ env.EMAIL_TO }}"
                    },
                    "template": "PTNT0D2WHE4MGFKBNTVPTRSBG3R7",
                    "data": {
                        "service": "Testing sending email using CI CD",
                        "env": $ENV,
                        "release": $RELEASE,
                        "tag": $TAG,
                        "task": $TASK,
                    }
                }
            }'
