name: Send Email Notification

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Echo Default Variables
        run: |
          echo "Branch: $GITHUB_REF"
          echo "Commit SHA: $GITHUB_SHA"
          echo "Actor: $GITHUB_ACTOR"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "EMAIL_TO: ${{ env.EMAIL_TO }}"
      - name: Define and Echo Custom Variables
        env:
          SERVICES: "Testing sending email using CI CD"
          ENV: "DEV"
          RELEASE: "Release_0.0.15"
          TAG: "Release_0.0.15"
          TASK: "POC sending Email from CI CD"
          DB: "N/A"
        run: |
          echo "SERVICES: $SERVICES"
          echo "ENV: $ENV"
          echo "RELEASE: $RELEASE"
          echo "TAG: $TAG"
          echo "TASK: $TASK"
          echo "DB: $DB"
      - name: List all Environment variables
        run: printenv
      - name: Send Email Notification
        run: |
            curl --location 'https://api.courier.com/send' \
            --header 'Authorization: Bearer pk_test_VR9ADX72AYMN7DQMBBR30P4QBJEX' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "message": {
                    "to": {
                        "email": "sthakur@ehs.com"
                    },
                    "template": "PTNT0D2WHE4MGFKBNTVPTRSBG3R7",
                    "data": {
                        "service": "Testing sending email using CI CD",
                        "env": "DEV",
                        "release": "Release_0.0.15",
                        "tag": "Release_0.0.15",
                        "task": "POC sending Email from CI CD"
                        "db": "N/A"
                    }
                }
            }'
