name: Send Email Notification

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to deploy'
        required: true
      environment:
        description: 'Environment (qa/demo/uat/prod)'
        choice:
        type: choice
        options:
            - qa
            - demo
            - uat
            - prod
        required: true 

jobs:
  send_email:
    runs-on: ubuntu-latest
    environment: DEV
    env:
      ENV: testENV     
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Echo Environment Variables
        run: |
           echo "EMAIL_TO: ${{ vars.EMAIL_TO }}"
           echo "RELEASE: ${{ vars.RELEASE }}"
           echo "TASK: ${{ vars.TASK }}"
           echo "ENV: $ENV"
           echo "version: ${{ inputs.version }}"
           echo "environment: ${{ inputs.environment }}"
      - name: Send Email Notification
        run: |
            curl --location 'https://api.courier.com/send' \
            --header 'Authorization: Bearer pk_test_VR9ADX72AYMN7DQMBBR30P4QBJEX' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "message": {
                    "to": {
                        "email": "${{ vars.EMAIL_TO }}"
                    },
                    "template": "PTNT0D2WHE4MGFKBNTVPTRSBG3R7",
                    "data": {
                        "service": "${{ vars.TASK }}",
                        "env": "'$ENV'",
                        "release": "${{ vars.RELEASE }}",
                        "tag": "${{ vars.RELEASE }}",
                        "task": "${{ vars.TASK }}",
                        "db": "Not Applicable"
                    }
                }
            }'
