name: Send Email Notification

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Echo Environment Variables
        run: |
           echo "EMAIL_TO: ${{ env.EMAIL_TO }}"
           echo "RELEASE: ${{ env.RELEASE }}"
           echo "TASK: ${{ env.TASK }}"
      - name: Send Email Notification
        run: |
            curl --location 'https://api.courier.com/send' \
            --header 'Authorization: Bearer pk_test_VR9ADX72AYMN7DQMBBR30P4QBJEX' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "message": {
                    "to": {
                        "email": "sthakur@ehs.com"
                    },
                    "template": "PTNT0D2WHE4MGFKBNTVPTRSBG3R7",
                    "data": {
                        "service": "CICD POC",
                        "env": "DEV",
                        "release": "Release_0.0.1",
                        "tag": "Release_0.0.3",
                        "task": "User Stories 1, User Stories 2",
                        "db": "Yes"
                    }
                }
            }'
